#!/bin/sh

################################################################################

ARCH=linux64

################################################################################

# Required for chroot
mount --verbose --types proc    /proc                           $STEAM_DIR/proc
mount --verbose --rbind         /sys                            $STEAM_DIR/sys
mount --verbose --make-rslave   $STEAM_DIR/sys
mount --verbose --rbind         /dev                            $STEAM_DIR/dev
mount --verbose --make-rslave   $STEAM_DIR/dev
mount --verbose --rbind         /run                            $STEAM_DIR/run
mount --verbose --make-rslave   $STEAM_DIR/run
mount --verbose --rbind         /var/db/repos/gentoo            $STEAM_DIR/var/db/repos/gentoo
mount --verbose --make-rslave   $STEAM_DIR/var/db/repos/gentoo

# Required for X
cp                              /home/wintcape/.Xauthority      $STEAM_DIR/home/steam/.Xauthority
ln    --force                   /tmp/.X11-unix/X0               $STEAM_DIR/tmp/.X11-unix/X0

# Required for pulseaudio
mount --verbose --rbind         /tmp                            $STEAM_DIR/tmp
mount --verbose --make-rslave   $STEAM_DIR/tmp
mount --verbose --rbind         /var/lib/dbus                   $STEAM_DIR/var/lib/dbus
mount --verbose --make-rslave   $STEAM_DIR/var/lib/dbus
mount --verbose --rbind         $XDG_RUNTIME_DIR                $STEAM_DIR$XDG_RUNTIME_DIR
mount --verbose --make-rslave   $STEAM_DIR$XDG_RUNTIME_DIR
mount --verbose --rbind         /home/wintcape/.pulse           $STEAM_DIR/home/steam/.pulse
mount --verbose --make-rslave   $STEAM_DIR/home/steam/.pulse
mount --verbose --rbind         /home/wintcape/.config/pulse    $STEAM_DIR/home/steam/.config/pulse
mount --verbose --make-rslave   $STEAM_DIR/home/steam/.config/pulse

exec -a steam-chroot alacritty --title 'steam-chroot' --config-file /home/wintcape/.config/alacritty/alacritty-chroot.yml -e $ARCH chroot $STEAM_DIR /bin/bash
