#!/bin/sh

kill $(pgrep steam-chroot)
umount --verbose $STEAM_DIR/proc
umount --verbose $STEAM_DIR/sys
umount --verbose $STEAM_DIR/dev
umount --verbose $STEAM_DIR/run
umount --verbose $STEAM_DIR/tmp
umount --verbose $STEAM_DIR/var/db/repos/gentoo
umount --verbose $STEAM_DIR/var/lib/dbus
umount --verbose $STEAM_DIR$XDG_RUNTIME_DIR
umount --verbose $STEAM_DIR/home/steam/.pulse
umount --verbose $STEAM_DIR/home/steam/.config/pulse
