#!/bin/sh

################################################################################

SRC_DIR=$HOME/.config/xmonad
EXE_NAME=xmonad

################################################################################

cd $SRC_DIR

# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML

# Do the build.
stack build

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(stack exec -- which $EXE_NAME) $1

# Build file cleanup.
rm -r ./src/*.hi ./src/*.o 2>/dev/null
