#!/bin/sh

################################################################################

SRC_DIR=$HOME/.config/xmonad
EXE_NAME=xmonad

################################################################################

cd $SRC_DIR

# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML

# Do the build.
stack build || exit 1

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(stack exec -- which $EXE_NAME) $HOME/.cache/xmonad/xmonad-x86_64-linux

# Build file cleanup.
rm -rf ./src/*.hi ./src/*.o
