#!/bin/sh

################################################################################

SRC_DIR=$HOME/.config/xmonad
EXE_NAME=xmonad

################################################################################

# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML

FAIL=0
cd $SRC_DIR

# Do the build.
stack build || FAIL=1

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T $(stack exec -- which $EXE_NAME) $1 || FAIL=2

# Build file cleanup.
rm ./src/*.hi ./src/*.o 2>/dev/null

exit $FAIL
